    $(function(){
        $("#include-pc").load("https://popozou.github.io/popozou.io/include-pc.html");
    })
    $(function(){
        $("#include-sns").load("https://popozou.github.io/popozou.io/include-sns.html");
    })
    $(function(){
        $("#include-sns-sports").load("https://popozou.github.io/popozou.io/include-sns-sports.html");
    })